name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ai_wellness_tracker/requirements.txt

    - name: Run Backend Sanity Check
      run: |
        cd ai_wellness_tracker/backend
        uvicorn main:app --port 9000 &
        sleep 5
        curl --fail http://127.0.0.1:9000 || exit 1
